# Generated by Django 6.0.2 on 2026-03-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events/')),
                ('event_date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('event_type', models.CharField(choices=[('private', 'Evento Privato'), ('business', 'Incontro Aziendale'), ('social', 'Social Dining'), ('theme', 'Cena a Tema')], default='social', max_length=20)),
                ('atmosphere', models.CharField(blank=True, max_length=255)),
                ('ideal_for', models.CharField(blank=True, max_length=255)),
                ('booking_url', models.URLField(blank=True)),
                ('cta_text', models.CharField(blank=True, default='Prenota un posto', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_date', 'order', 'id'],
            },
        ),
    ]
