# Generated by Django 6.0.2 on 2026-05-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0003_eventcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commento evento', 'verbose_name_plural': 'Commenti eventi'},
        ),
    ]
