# Generated by Django 6.0.2 on 2026-05-15 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('newsletter_events', 'Newsletter eventi')], max_length=50)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('policy_version', models.CharField(default='1.0', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consenso utente',
                'verbose_name_plural': 'Consensi utente',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
